### PR TITLE
TGT-113: openocd_zephyr: bump to sdk-ng v1.16.1 version

### PR DESCRIPTION
**Pull request by IvoBCD**
Bump openocd_zephyr version, to better support programming newer STM32 Nucleo boards.

### CODE REVIEW

**Review by JeremyBCD — APPROVED** [review]

**Comment by IvoBCD** [comment]
@JeremyBCD @erauer Having trouble building/testing this locally; I don't think the patches will apply cleanly.

**Comment by IvoBCD** [comment]
somehow, keep getting

```
nitialized empty Git repository in /home/ivo/.nerves/dl/openocd_zephyr/git/.git/
GIT_DIR=/home/ivo/.nerves/dl/openocd_zephyr/git/.git git remote add origin 'git://github.com/zephyrproject-rtos/openocd.git' 
GIT_DIR=/home/ivo/.nerves/dl/openocd_zephyr/git/.git git remote set-url origin 'git://github.com/zephyrproject-rtos/openocd.git' 
Fetching all references
GIT_DIR=/home/ivo/.nerves/dl/openocd_zephyr/git/.git git fetch origin 
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out

Detected a corrupted git cache.
This is the second time in a row; bailing out
```
when changing the requested upsteam rev, but not with the original one

**Comment by IvoBCD** [comment]
Same issue on https://github.com/bcdevices/ly10-buildroot-packages/pull/34

**Comment by erauer** [comment]
@IvoBCD I'm confident in removing the jimctl patch but the structure of the code for the efm32 code has changed so much, I don't know how to evaluate. Looks like you originally patched it for https://bcdevices.atlassian.net/browse/TGT-32 .

**Comment by IvoBCD** [comment]
@erauer What I patched seems fixed upstream in https://github.com/zephyrproject-rtos/openocd/commit/e406f2b0dce0b7c6974ca715700f445e2580a36d

**Comment by IvoBCD** [comment]
still getting "github.com[0: 140.82.121.3]: errno=Connection timed out".
I also get this with `git clone git://github.com/zephyrproject-rtos/openocd.git`.  I think I need to use

```
OPENOCD_ZEPHYR_SITE = $(call github,zephyrproject-rtos,openocd,$(OPENOCD_ZEPHYR_VERION))
```

but that fails with:

```
IMPORTANT: If you update nerves_system_br, you should rerun this script.
** (Mix) Nerves encountered an error while constructing the artifact
make[1]: Entering directory '/home/ivo/src/GIT/bcd/ly11-system-rpi4/.nerves/artifacts/ly11_system_rpi4-portable-0.24.3'
/home/ivo/src/GIT/bcd/ly11-system-rpi4/package/openocd_zephyr/openocd_zephyr.mk:57: *** OPENOCD_ZEPHYR_SITE (https://github.com/zephyrproject-rtos/openocd/archive/) cannot have a trailing slash.  Stop.
make[1]: *** [Makefile:23: _all] Error 2
make[1]: Leaving directory '/home/ivo/src/GIT/bcd/ly11-system-rpi4/.nerves/artifacts/ly11_system_rpi4-portable-0.24.3'


make: *** [Makefile:86: build] Error 1
```

**Comment by IvoBCD** [comment]
@erauer Building locally with `git config --global url."https://github.com/".insteadOf git://github.com/` (as CI does) works for me; maybe you have that in your global git config ?

**Pull request merged**
