### PR TITLE
Add openocd_maxim.

### PR DESCRIPTION
**Pull request by JeremyBCD**
@erauer How do you generate the .hash files for packages?

### CODE REVIEW

**Comment by erauer** [comment]
@JeremyBCD I use `sha256sum` , for example `sha256sum pyocd-0.34.1.tar.gz`.  Seems like the convention is to use `# Locally computed` comment in the case that the upstream source didn't provide it.

**Comment by JeremyBCD** [comment]
@erauer How are you making the .tar.gz?

**Comment by erauer** [comment]
@JeremyBCD I wish I had a better way (maybe too  easy to do it the wrong ways):

1. In ly11_system_rpi4, moved the package symlink to a local checkout of `ly10-buildroot-packages` 
2. I let the download fail and then found the package in `~/.nerves/dl` and ran `sha256sum openocd_maxim-56a818e4c5a9655980107e576317f7c5ed610292-br1.tar.gz`

**Review by erauer — APPROVED** [review]

**Comment by JeremyBCD** [comment]
Ah, ok. I'll do that next time.

**Pull request merged**
